// vue-socketio-app/src/components/MessageInput/MessageInput.vue
<script setup lang="ts">
defineProps<{
  value: string;
  onChange: (value: string) => void;
  onSend: () => void;
  onKeyPress: (e: KeyboardEvent) => void;
  disabled: boolean;
}>();
</script>

<template>
  <div class="message-input-section">
    <input
      type="text"
      placeholder="Type your message..."
      :value="value"
      @input="(e) => onChange((e.target as HTMLInputElement).value)"
      @keydown="onKeyPress"
      class="message-input"
    />
    <button @click="onSend" :disabled="disabled" class="send-button">
      Send
    </button>
  </div>
</template>

// react-socketio-app/src/components/MessageInput/MessageInput.tsx
import React from "react";

interface MessageInputProps {
  value: string;
  onChange: (value: string) => void;
  onSend: () => void;
  onKeyPress: (e: React.KeyboardEvent<HTMLInputElement>) => void;
  disabled: boolean;
}

export const MessageInput: React.FC<MessageInputProps> = ({
  value,
  onChange,
  onSend,
  onKeyPress,
  disabled,
}) => {
  return (
    <div className="message-input-section">
      <input
        type="text"
        placeholder="Type your message..."
        value={value}
        onChange={(e) => onChange(e.target.value)}
        onKeyDown={onKeyPress}
        className="message-input"
      />
      <button onClick={onSend} disabled={disabled} className="send-button">
        Send
      </button>
    </div>
  );
};

export default MessageInput;
