// react-socketio-app/src/components/MessagesArea/MessagesArea.tsx
import React from "react";

interface MessagesAreaProps {
  messages: string[];
  currentUsername: string;
}

export const MessagesArea: React.FC<MessagesAreaProps> = ({
  messages,
  currentUsername,
}) => {
  return (
    <div className="messages-area">
      {messages.length === 0 ? (
        <p className="no-messages">No messages yet</p>
      ) : (
        messages.map((msg, index) => (
          <div
            key={index}
            className={`message ${msg.startsWith(`${currentUsername}:`) ? "own-message" : ""}`}
          >
            {msg.startsWith(`${currentUsername}:`) && (
              <span className="you-tag">(you) </span>
            )}
            {msg}
          </div>
        ))
      )}
    </div>
  );
};

export default MessagesArea;

// vue-socketio-app/src/components/MessagesArea/MessagesArea.vue
<script setup lang="ts">
defineProps<{
  messages: string[];
  currentUsername: string;
}>();
</script>

<template>
  <div class="messages-area">
    <p v-if="messages.length === 0" class="no-messages">No messages yet</p>
    <div
      v-else
      v-for="(msg, index) in messages"
      :key="index"
      class="message"
      :class="{ 'own-message': msg.startsWith(currentUsername + ':') }"
    >
      <span v-if="msg.startsWith(currentUsername + ':')" class="you-tag"
        >(you)</span
      >
      {{ msg }}
    </div>
  </div>
</template>
