// react-socketio-app/src/components/StatusBadge/StatusBadge.tsx
import React from "react";

interface StatusBadgeProps {
  isConnected: boolean;
  username: string;
}

export const StatusBadge: React.FC<StatusBadgeProps> = ({
  isConnected,
  username,
}) => {
  return (
    <div
      className={`status-badge ${isConnected ? "connected" : "disconnected"}`}
    >
      {isConnected
        ? `✓ Connected as ${username}`
        : "✗ Not connected to backend"}
    </div>
  );
};

export default StatusBadge;

// vue-socketio-app/src/components/StatusBadge/StatusBadge.vue
<script setup lang="ts">
defineProps<{
  isConnected: boolean;
  username: string;
}>();
</script>

<template>
  <div class="status-badge" :class="isConnected ? 'connected' : 'disconnected'">
    {{
      isConnected ? `✓ Connected as ${username}` : "✗ Not connected to backend"
    }}
  </div>
</template>
